pipeline {
    agent any
  
    stages {
        stage("permiso") {
            steps {
		script {
	                sh 'chmod +x ./clase11/main.sh'
			sh 'main.sh'
			//sh "ls"
		}            
	   }   
        }
    }
}
