pipeline {
    agent any
  
    stages {
        stage("permiso") {
            steps {
                sh 'chmod +x main.sh'
            }
        }
        stage("ejecucion") {
            steps {
                sh 'main.sh'
            }   
        }
    }
}
