apiVersion: v1
kind: Service
metadata:
  name: educacionit-app-service
spec:
  ports:
  - name: "3000"
    port: {{ .Values.service.port }} #3000
    targetPort: {{ .Values.service.port }} #3000
  selector:
    app: "{{ .Chart.Name }}" #educacionit-app
  type: LoadBalancer