apiVersion: v1
kind: Service
metadata:
  name: db-server-service
spec:
  ports:
    - name: "27017"
      port: {{ .Values.mongoDB.port }} #27017
      targetPort:  {{ .Values.mongoDB.port }} #27017
  selector:
    app: "{{ .Values.mongoDB.name }}" #db-server